---

name: convert drawio to png
on:
  workflow_dispatch:
  push:
    branches:
      -main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Convert digramm to png
        uses: Burnett01/actions-drawio@1.2
        with:
          src: outputs/architecture.drawio
          dest: outputs/architecture.png

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit PDF to the repository
        run: |
          git add outputs/architecture.png
          git commit -m "Add/update png output"
          git push origin main
        env:
          GH_TOKEN: ${{ github.token }}
