---
name: Export Drawio to PNG

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'diagram/architecture.drawio'
      - '.github/workflows/drawio_export.yml'

jobs:
  export-drawio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download Drawio Desktop App
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v21.2.3/drawio-x86_64-21.2.3.AppImage -O drawio.AppImage
          chmod +x drawio.AppImage

      - name: Export Drawio to PNG
        run: |
          ./drawio.AppImage --export --format png --output diagram/architecture.png diagram/architecture.drawio

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit PDF to the repository
        run: |
          git add diagram/architecture.png
          git commit -m "Add/update Diagram in PNG Format"
          git push origin main
        env:
          GH_TOKEN: ${{ github.token }}
