---
name: Export Drawio to PNG

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'diagram/architecture.drawio'
      - '.github/workflows/drawio_export.yml'

jobs:
  export-drawio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb
  
      - name: Download Drawio Desktop App
        run: |
          wget https://github.com/jgraph/drawio-desktop/releases/download/v21.4.0/drawio-x86_64-21.4.0.AppImage -O drawio.AppImage
          chmod +x drawio.AppImage
  
      - name: Extract Drawio AppImage
        run: |
          ./drawio.AppImage --appimage-extract
          ls squashfs-root  # Verify extraction
  
      - name: Export Drawio to PNG using Xvfb
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" ./squashfs-root/drawio --export --format png --output diagram/architecture.png diagram/architecture.drawio

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit PDF to the repository
        run: |
          git add diagram/architecture.png
          git commit -m "Add/update Diagram in PNG Format"
          git push origin main
        env:
          GH_TOKEN: ${{ github.token }}
